name: OrangeFox Recovery Build

on:
  workflow_dispatch:
    inputs:
      clean_ccache:
        description: "Delete ccache before build?"
        required: true
        type: choice
        default: "no"
        options:
          - "no"
          - "yes"

jobs:
  build:
    name: Build Recovery
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CCACHE_DIR: /tmp/ccache
      CCACHE_EXEC: /usr/bin/ccache  
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Install ccache ONLY if not cleaning
      - name: Install ccache
        if: github.event.inputs.clean_ccache == 'no'
        run: sudo apt update && sudo apt install -y ccache

      # Restore cache ONLY if not cleaning
      - name: Setup ccache
        if: github.event.inputs.clean_ccache == 'no'
        uses: actions/cache@v5
        with:
         path: ${{ env.CCACHE_DIR }}
         key: ccache-${{ runner.os }}-ofox-${{ github.run_id }}
         restore-keys: |
           ccache-${{ runner.os }}-ofox-


      # Delete cache completely if requested
      - name: Remove ccache completely
        if: github.event.inputs.clean_ccache == 'yes'
        run: |
          sudo rm -rf ${{ env.CCACHE_DIR }}
          echo "ccache removed successfully"

      # Configure ccache ONLY if not cleaning
      - name: Configure ccache
        if: github.event.inputs.clean_ccache == 'no'
        run: |
          mkdir -p ${{ env.CCACHE_DIR }}
          ccache --set-config=cache_dir=${{ env.CCACHE_DIR }}
          ccache --set-config=temporary_dir=/tmp/ccache-tmp
          ccache -M 10G

      - name: Build Environment
        run: |
          git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
          cd scripts
          sudo bash setup/android_build_env.sh

      - name: Set-up Manifest
        run: |
          export MANIFEST_BRANCH=12.1
          mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
          cd ${GITHUB_WORKSPACE}/OrangeFox
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git clone https://gitlab.com/OrangeFox/sync.git -b master
          cd sync
          ./orangefox_sync.sh --branch $MANIFEST_BRANCH --path ${GITHUB_WORKSPACE}/OrangeFox/fox_$MANIFEST_BRANCH

      - name: Clone Device Tree
        run: |
          export DEVICE_TREE=https://github.com/nitejjaiswal/orangefox_device_lava_LXX506
          export DEVICE_TREE_BRANCH=main
          export DEVICE_PATH=device/lava/LXX506
          export MANIFEST_BRANCH=12.1

          cd ${GITHUB_WORKSPACE}/OrangeFox/fox_$MANIFEST_BRANCH
          git clone $DEVICE_TREE -b $DEVICE_TREE_BRANCH ./$DEVICE_PATH
          cd $DEVICE_PATH
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Building OrangeFox
        run: |
          export DEVICE_NAME=LXX506
          export BUILD_TARGET=boot
          export MANIFEST_BRANCH=12.1
          cd ${GITHUB_WORKSPACE}/OrangeFox/fox_$MANIFEST_BRANCH      
          set +e
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export USE_CCACHE=1
          set -e     
          lunch omni_${DEVICE_NAME}-eng
          mka adbd ${BUILD_TARGET}image
          mv out/target/product/${DEVICE_NAME}/boot.img \
             out/target/product/${DEVICE_NAME}/ofox.img

      # Show stats ONLY if ccache used
      - name: Cache Stats
        if: github.event.inputs.clean_ccache == 'no'
        run: ccache -s

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            OrangeFox/fox_12.1/out/target/product/LXX506/ofox.img
          name: OrangeFox Recovery for Lava Blaze 5G (LXX506)
          tag_name: ${{ github.run_id }}
          body: |
            OrangeFox Recovery Build - Unofficial 
            
            Device: Lava Blaze 5G
            Codename: LXX506
            Recovery Image: ofox.img
            
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-LXX506-12.1
          path: OrangeFox/fox_12.1/out/target/product/LXX506/ofox.img
          retention-days: 30
