name: TWRP Recovery Build

on:
  workflow_dispatch:
    inputs:
      clean_ccache:
        description: "Delete ccache before build?"
        required: true
        type: choice
        default: "no"
        options:
          - "no"
          - "yes"

jobs:
  build:
    name: Build Recovery
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CCACHE_DIR: /tmp/ccache
      CCACHE_EXEC: /usr/bin/ccache  
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Install ccache ONLY if not cleaning
      - name: Install ccache
        if: github.event.inputs.clean_ccache == 'no'
        run: sudo apt update && sudo apt install -y ccache

      # Restore cache ONLY if not cleaning
      - name: Setup ccache
        if: github.event.inputs.clean_ccache == 'no'
        uses: actions/cache@v5
        with:
         path: ${{ env.CCACHE_DIR }}
         key: ccache-${{ runner.os }}-twrp-${{ github.run_id }}
         restore-keys: |
           ccache-${{ runner.os }}-twrp-

      # Delete cache completely if requested
      - name: Remove ccache completely
        if: github.event.inputs.clean_ccache == 'yes'
        run: |
          sudo rm -rf ${{ env.CCACHE_DIR }}
          echo "ccache removed successfully"

      # Configure ccache ONLY if not cleaning
      - name: Configure ccache
        if: github.event.inputs.clean_ccache == 'no'
        run: |
          mkdir -p ${{ env.CCACHE_DIR }}
          chmod 777 ${{ env.CCACHE_DIR }}
          ccache --set-config=cache_dir=${{ env.CCACHE_DIR }}
          ccache --set-config=temporary_dir=/tmp/ccache-tmp
          ccache -M 5G
          
      - name: Build Environment
        run: |
          sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
          sudo chmod a+x /usr/local/bin/repo
          repo --version

      - name: Set-up Manifest
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/twrp
          cd ${GITHUB_WORKSPACE}/twrp
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Clone Device Tree
        run: |
          export DEVICE_TREE=https://github.com/ayusc/orangefox_device_lava_LXX506
          export DEVICE_TREE_BRANCH=main
          export DEVICE_PATH=device/lava/LXX506

          cd ${GITHUB_WORKSPACE}/twrp
          git clone $DEVICE_TREE -b $DEVICE_TREE_BRANCH ./$DEVICE_PATH
          cd $DEVICE_PATH
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Building TWRP
        run: |
          export DEVICE_NAME=LXX506
          export BUILD_TARGET=boot
          cd ${GITHUB_WORKSPACE}/twrp
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export USE_CCACHE=1
          lunch omni_${DEVICE_NAME}-eng
          mka adbd ${BUILD_TARGET}image
          mv out/target/product/${DEVICE_NAME}/boot.img out/target/product/${DEVICE_NAME}/twrp.img

      # Show stats ONLY if ccache used
      - name: Cache Stats
        if: github.event.inputs.clean_ccache == 'no'
        run: ccache -s

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            twrp/out/target/product/LXX506/twrp.img
          name: TWRP Recovery for Lava Blaze 5G (LXX506)
          tag_name: ${{ github.run_id }}
          body: |
            TWRP Recovery Build - Unofficial
            
            Device: Lava Blaze 5G
            Codename: LXX506
            Recovery Image: twrp.img
            
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-LXX506
          path: twrp/out/target/product/LXX506/twrp.img
          retention-days: 30
